[package]
name = "deuxfleurs"
version = "0.1.0"
edition = "2024"
keywords = ["wgpu", "graphics", "geometry", "mesh"]
license = "MIT"
description = "Viewer for geometry processing data (surface meshes, point clouds, scalar field...)"
repository = "https://github.com/Lieunoir/deuxfleurs"
exclude = ["examples/*"]

[dependencies]
bytemuck = { version = "1.12.1", features = ["derive"] }
glam = { version = "0.32", features = ["serde"] }
egui = "0.34"
transform-gizmo-egui = "0.9"
egui-wgpu = { version = "0.34", features = ["winit"] }
egui-winit = { version = "0.34", default-features = false }
egui_plot = "0.35"
env_logger = { version = "0.9.1", optional = true }
image = { version = "0.24.4", default-features = false, features = ["png"] }
log = "0.4.17"
oneshot = "0.1.5"
pollster = "0.2.5"
rfd = { version = "0.15", default-features = false, features = [
    "xdg-portal",
    "async-std",
], optional = true }
wgpu = "29"
winit = { version = "0.30", default-features = false, features = ["rwh_06"] }
ndarray = { version = "0.15", optional = true }
nalgebra = { version = "0.32", optional = true }
indexmap = { version = "2.2.3" }
rand = { version = "0.9", default-features = false, features = ["small_rng"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
memchr = "2.7.4"
atoi_radix10 = { version = "0.0.1", features = ["simd"] }
num-traits = "0.2.19"
serde_cbor = { version = "0.11.2", optional = true }
wgpu-profiler = { version = "=0.27.0", features = ["tracy"] , optional = true}
tracy-client = {version = "0.18.2", optional = true}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit = { version = "0.34", default-features = false, features = [
    "clipboard",
] }

[features]
default = ["x11"]
# Enable ndarray types as input
ndarray = ["dep:ndarray"]
# Enable nalgebra types as input
nalgebra = ["dep:nalgebra"]
# Add ui loadSurfaceButton component
#
# Optional as this requires several more dependencies
surface_button = ["dep:rfd"]
# Allow loading/saving state (from ui and programmatically)
#
# Add Serialization/Deserialization to several components,
# with noticeable negative effect on compile times.
saves = ["dep:rfd", "wgpu/serde", "indexmap/serde", "dep:serde_cbor"]
# Starts logging at launch
logger = ["dep:env_logger"]
# Enable X11 winit backend
x11 = ["egui-winit/x11", "winit/x11"]
# Enable Wayland winit backend
wayland = ["egui-winit/wayland", "winit/wayland", "winit/wayland-dlopen"]
# Enables wgpu profiler
profiling = ["dep:wgpu-profiler", "dep:tracy-client"]

[dev-dependencies]
faer = "0.24"
rayon = "1.10.0"
fast-svd-3x3 = "0.2.0"

[[example]]
name = "load_filter"
path = "examples/load_filter.rs"
required-features = ["surface_button"]

[[example]]
name = "load_state"
path = "examples/load_state.rs"
required-features = ["saves"]

# WASM specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
getrandom = { version = "0.2", features = ["js"] }
wgpu = { version = "=29", default-features = false, features = ["webgl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.64", features = [
    "Document",
    "Window",
    "Element",
    "Location",
    "Clipboard",
    "Request",
    "RequestMode",
    "RequestInit",
    "Response",
] }
js-sys = "0.3.64"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
